sudo: required

language: node_js

node_js:
  - 12  

services:
  - docker

before_install:
  - docker build -t mikemorris101/docker-react -f Dockerfile.dev .

script:
 - docker run mikemorris101/docker-react npm run test -- --coverage